# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd
  build:
    cmds:
      - go build -o ./bin/nats-hash-svc.exe ./cmd
  exec:
    cmds:
      - ./bin/nats-hash-svc.exe
